// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhmicelinsyzjhjiznqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxobWljZWxpbnN5empoaml6bnFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NzAwMTcsImV4cCI6MjA1NjQ0NjAxN30.PA_0ILn7L0cCxjk6UbzKhZpysNxJcdN8N_7OkeGMDP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);